version: "3.10"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - storage

  url_shorterner:
    build: .
    ports:
      - "5000:5000"
    environment:
      REDIS_PORT: "6379"
      REDIS_HOST: "redis"
      SERVICE_URL: "http://0.0.0.0:5000"
      SERVICE_PORT: "5000"
    networks:
      - storage

networks:
  storage:
